# Generated by Django 3.2.8 on 2021-12-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footimgapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footimg',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='footimg',
            old_name='message',
            new_name='message1',
        ),
        migrations.RenameField(
            model_name='footimg',
            old_name='nickname',
            new_name='nickname1',
        ),
        migrations.AddField(
            model_name='footimg',
            name='image2',
            field=models.ImageField(null=True, upload_to='footimg/'),
        ),
        migrations.AddField(
            model_name='footimg',
            name='image3',
            field=models.ImageField(null=True, upload_to='footimg/'),
        ),
        migrations.AddField(
            model_name='footimg',
            name='message2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footimg',
            name='message3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footimg',
            name='nickname2',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='footimg',
            name='nickname3',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
